# Generated by Django 3.1.1 on 2020-09-30 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=12, unique=True,
                                              validators=[django.core.validators.MinLengthValidator(limit_value=12)])),
                ('lastname', models.CharField(max_length=25)),
                ('firstname', models.CharField(max_length=25)),
                ('patronymic', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=25)),
                ('house', models.CharField(max_length=5)),
                ('apartment', models.CharField(blank=True, max_length=5, null=True)),
                ('whatsupp', models.CharField(blank=True, max_length=12, null=True)),
                ('telegram', models.CharField(blank=True, max_length=12, null=True))
            ],
        ),
    ]
