# Generated by Django 3.1.1 on 2020-09-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=11, unique=True),
        ),
    ]
