# Generated by Django 3.1.1 on 2020-10-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0002_auto_20201001_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
